name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        description: Image to build and push
        options:
          - intercepting-communication

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.event.inputs.image }}
          push: true
          tags: pwncollege/challenge-${{ github.event.inputs.image }}:latest
